### PR TITLE
Mechs & Mercs: Black Talons(273960), Chroma Squad(251130), StarCrawlers(318970)  and Lux Delux(341950) works.

### PR DESCRIPTION
**Pull request by cristianedson**
Sources:
Chroma Squad: http://www.gamingonlinux.com/articles/revisiting-my-childhood-with-%E2%80%98chroma-squad%E2%80%99-now-on-linux.5313

StarCrawlers: http://www.gamingonlinux.com/articles/starcrawlers-an-early-mix-of-rpg-dungeon-crawling-released-for-linux-thoughts-thrown-in.5150

Mechs & Mercs: Black Talons: http://www.gamingonlinux.com/articles/mechs-mercs-black-talons-a-real-time-strategy-game-we-take-a-gander.5010

Lux Delux
Comment of page bellow.
http://www.gamingonlinux.com/articles/lux-delux-a-risk-styled-game-now-on-steam-for-linux.5323

### CODE REVIEW

**Comment by johndrinkwater** [comment]
Thanks for this submission; 318970 has been inserted at the wrong point, if you can amend the commit, I can merge.

It also appears our test is outputting an incorrect message, so I shall correct that :^)
1) SteamLinuxTest::testSorting
File must be sorted correctly by appid, problem at "319050"
Failed asserting that 318970 matches expected 319050.

**Comment by Tele42** [comment]
Lux Delux - 341950 is also not sorted.

**Comment by johndrinkwater** [comment]
Travis at least now outputs better information as of 099fb3c422, see CONTRIBUTING to learn how to run this test locally before commits :) 

```
1) SteamLinuxTest::testSorting
File must be sorted correctly by appid, "318970" is far too late
Failed asserting that 318970 matches expected 319050.
```

**Comment by johndrinkwater** [comment]
Thanks!

**Comment by cristianedson** [comment]
Thanks for spoting my error and sorry to not check my email sooner and don't make the validation.

**Pull request merged**
