### PR TITLE
Dragon Fantasy I and Neon Struct work

### PR DESCRIPTION
**Pull request by adolson**

### CODE REVIEW

**Comment by johndrinkwater** [comment]
Sorry for the slow feedback, this failed our CI check as it is using spaces rather than tabs, if you would correct that, I can merge it straight away.
Thanks!

**Comment by johndrinkwater** [comment]
I feel bad that I didn’t check these titles before I merged; Neon Struct is a month away from launch, how can it be verified as working?

**Comment by adolson** [comment]
David Pittman sent me a Steam key which I redeemed.. It installed and runs
fine on Debian 64-bit, with gamepad support too.

**Comment by johndrinkwater** [comment]
OK, just verifying as we have to be careful with submissions of the sort - as preview builds via developer subs don’t always match regular Steam sub behaviour.

**Pull request merged**
