### PR TITLE
Update GAMES.json

### PR DESCRIPTION
**Pull request by adolson**
confirmed several games in my library

### CODE REVIEW

**Comment by Tele42** [comment]
305500: Trapped Dead: Lockdown
322680: BLACKHOLE
340300: Teddy Floppy Ear - Mountain Adventure
340310: Teddy Floppy Ear - Kayaking
352960: Star Horizon
360520: Hypt
360640: 12 Labours of Hercules II: The Cretan Bull
361190: Sparkle 3 Genesis
361430: The Little Crane That Could
368830: Adventure in the Tower of Flight
375120: Super Star Path

**Comment by adolson** [comment]
OK. Which ones?

**Comment by Tele42** [comment]
Trapped Dead: Lockdown, The Little Crane That Could

**Comment by adolson** [comment]
OK. And how can we tell this for the future? Maybe it should be in the instructions, if it's going to hold up merges.

**Comment by Tele42** [comment]
I saw the hints on https://steamdb.info/linux/?other when looking up the game titles.

**Comment by adolson** [comment]
Ah, I see. So it's somehow automated, but only for games that aren't confirmed as working? Seems kinda weird.

**Comment by xPaw** [comment]
Confirmed games in this list are skipped from all linux checks to speed up processing, thus we can't display that information on confirmed games.

**Comment by adolson** [comment]
Gotcha. But if a dev adds a 32-bit launch config to a confirmed game, then the info here becomes outdated. Aside from trying to keep tabs on all 600-something of my games manually, is there some way to tell this info easily to try and keep the info here accurate?

**Comment by xPaw** [comment]
@adolson Can you fix (rebase?) your pull request so we can merge it?

**Comment by adolson** [comment]
Yeah, no. I don't know how to properly do that, so I'll just close this and redo it all when I have time.

**Pull request closed without merging**
