### PR TITLE
Working games

### PR DESCRIPTION
**Pull request by JasonRivers**
911 Operator, F1 2017 & Think To Die 3 all work.

### CODE REVIEW

**Comment by johndrinkwater** [comment]
Thanks for the PR, would you remove the no icon comment as we don’t want to store that, commit message can include that info though. https://github.com/SteamDatabase/SteamLinux/pull/606/commits/febcfeeea8d492b32cd0bea589e86c7992f376f1

Managed to merge the same comment in September that I didn’t notice at the time and will remove it once your changes are in – my mistake.

**Comment by JasonRivers** [comment]
Done, As it was the first commit I did I couldn't squash them, I can create a fresh PR if you prefer

**Comment by johndrinkwater** [comment]
To fix up the commits you can do: 
* `git rebase --interactive 'febcfee^'`
* replace pick with edit for `febcfee`
* move the line for `bd77335` to below `febcfee` and replace pick with squash, save and exit editor
* edit `GAMES.json` to have the correct modification (if the squash worked above, it should be correct already)
* `git commit --all --amend` to commit while retaining original commit message
* `git rebase --continue` to get up to date with the last commit `6451c0d` which will now have a new hash
* `git push --force master` to get it up to date on your github fork which should automatically refresh this PR :)

Or I can just merge it, tell me what you prefer 😄

**Comment by JasonRivers** [comment]
As it's already pushed, let's just merge, next time I won't put the comment in the JSON :p

**Comment by johndrinkwater** [comment]
Hm, web editor cannot seem to resolve the conflicts with this branch.

**Comment by johndrinkwater** [comment]
Fixed up in CLI and pushed with https://github.com/SteamDatabase/SteamLinux/commit/7227d1a6a6c56834cf51715f63cc58c9b7557a56, thanks for the contrib!

**Pull request closed without merging**
