### PR TITLE
Sunrider Academy (340730) works

### PR DESCRIPTION
**Pull request by RyuzakiKK**

### CODE REVIEW

**Comment by johndrinkwater** [comment]
Hey @RyuzakiKK, just wanted to check you’ve been able to play this through getting it on Steam? It wasn’t with the demo 340740?

**Comment by RyuzakiKK** [comment]
I personally tried the demo and it works. Also this guy confirmed that the full game works on Linux http://steamcommunity.com/app/340730/discussions/0/610573009244270155/

**Comment by johndrinkwater** [comment]
OK :) For future patches, if you’re not able to confirm that appid yourself, would you include some info (like that link) to help us verify the claim.
Trying to avoid accidental inclusion of faulty data, you see…

**Comment by RyuzakiKK** [comment]
Ok, I'll do next time.

**Pull request merged**
