### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by xPaw**
@johndrinkwater

### CODE REVIEW

**Comment by johndrinkwater** [comment]
Agree that we should have a declaration on the data we store, and PD is the way to go. However unlicense is a pretty poor ‘licence’ and believe CC-0 would be a better fit with our audience of contributors.
https://github.com/github/gitignore/blob/master/LICENSE is a good copy/pastable replacement if that’s is acceptable.
Welcome to discuss it.

**Comment by xPaw** [comment]
I'm fine with CC0.

**Comment by RyuzakiKK** [comment]
I agree with CC0

**Comment by xPaw** [comment]
cc @psymin, @frostworx, @hypercephalickitten, @soeb, @weltall, @seeeeew, @LiamDawe, @BlaXpirit, @Daverball

**Comment by Daverball** [comment]
CC0 seems like the way to go in this case.

**Comment by LiamDawe** [comment]
CC0 seems like a good and fair license.

**Comment by soeb** [comment]
Definitely CC0.

**Comment by frostworx** [comment]
now after it got merged I'd say everything but CC0!
jk, CC0 is fine :}

**Pull request merged**
