### PR TITLE
Signal The End of Football

### PR DESCRIPTION
**Pull request by AimHere**
The Signal from Tölva (457760) works
The End is Nigh (583470) works
 Football Manager 2018 (624090) works

### CODE REVIEW

**Comment by johndrinkwater** [comment]
Hmm, The End Is Nigh has Linux missing from their other Steam subs, dev comp + CD Key, will need to poke them over the latter.

**Comment by AimHere** [comment]
Oh, I forgot that The End is Nigh only works by selecting the (unpassworded) beta. I don't know if that is something that should affect it's database status.

**Comment by johndrinkwater** [comment]
Typically we note passwords for betas if they have them, but still include their entry in the list. So it seemed correct.

It’s no longer beta as of today https://twitter.com/icculus/status/940445379878891520

**Comment by johndrinkwater** [comment]
The End is Nigh is now all sorted.

**Pull request merged**
